# Generated by Django 4.2.5 on 2023-10-12 23:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blogging", "0002_category"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Category",
        ),
    ]
