# Generated by Django 4.2.5 on 2023-10-12 23:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blogging", "0004_post_description_post_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="description",
            new_name="catagory_description",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="name",
            new_name="catagory_name",
        ),
    ]
