# Generated by Django 4.2.5 on 2023-10-14 00:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogging", "0005_rename_description_post_catagory_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="catagory_description",
        ),
        migrations.RemoveField(
            model_name="post",
            name="catagory_name",
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True)),
                (
                    "posts",
                    models.ManyToManyField(
                        blank=True, related_name="categories", to="blogging.post"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
    ]
